### ISSUE TITLE
Threaded user notes

### ISSUE THREAD

**Issue by PeeHaa** [morrisonlevi/web-php#3]
The current user notes contain people starting their notes with: "In response to", "to clarify foo's message" etc.

Maybe we can provide a way to actually reply to an existing user note and either have levels or some either way to display the relation to the parent.

**Comment by Wes1262** [comment]
Visually nested stuff is usually a mess to style, because the horizontal space will eventually finish after N levels of indentation. An "hypertext" option could be "This message [is referenced by|refers to] [link#1901] [link#3919]" or something, but a better option might be sorting root messages by votes, then limit answers to say max 3 depth and order them by datetime.

**Comment by kelunik** [comment]
I guess even one level might be enough. Most user notes should anyway be deleted and integrated into the documentation itself.

**Comment by morrisonlevi** [comment]
Actually we have intentionally started deleting or modifying "in response to" comments. We did this when we allowed people to vote on comments because it broke the linear progression. Please feel free to delete or modify any such notes. I'm open to hear your suggestions but if it was up to me I'd say let's keep a single level.

**Comment by morrisonlevi** [comment]
I'll close this as wontfix; I just realized everyone has already pitched in their $0.02. We can revisit this later but for now we'll completely de-prioritize it.
